### ISSUE TITLE
Example without Rails?

### ISSUE THREAD

**Issue by alecgorge** [Moesif/moesif-rack#16]
Based on the name of this repo it seems like I can use Moesif without needing Rails, but all of the examples use Rails and Rails APIs.

Are there any examples of using `moesif-rack` with vanilla Rack?

**Comment by dgilling** [comment]
Hi @alecgorge, yes it can be used without rails but we don't have an example with vanilla Rack. We can work on one and publish it.

**Comment by dgilling** [comment]
We have a generic Rack example now available here: https://github.com/Moesif/moesif-rack-example
